#!/usr/bin/env bash
#
# sizable :: print largest n files and/or directories with their unit size
# requires: bash 4.0+, find, sort, du, xargs, head, realpath

trap 'echo -e "\nSIGINT Received... exiting"; exit 130' SIGINT

err() {
  # send errors to standard error
  echo "[${0##*/}] error: $*" >&2
}

warn() {
  # send warnings to standard error
  echo "[${0##*/}] warning: $*" >&2
}

show_help() {
  # help option text
  echo "Usage: ${0##*/} [-d] [-f] [-n <number>] [<directory>]"
  echo "Options:"
  echo "  -h, --help    Show this help menu"
  echo "  -d            Show directories"
  echo "  -f            Show files (DEFAULT=True)"
  echo "                - (Only needed when using '-d' to print files and dirs)"
  echo "  -n <int>      Number of lines to show (DEFAULT=10)"
}

_parse_options() {
  # parse arguments and assign variables

  # check for long "--help"
  if [[ "$1" == "--help" ]]; then
    show_help
    showed_help="1"
    return 0
  fi

  # required: headcount, show_dirs, show_files variables
  # need to be declared before this function
  local opt
  while getopts ":hdfn:" opt; do
    case "$opt" in
      h)
        show_help
        showed_help="1"
        return 0
        ;;
      d)
        show_dirs="1"
        show_files=
        ;;
      f) show_files="1" ;;
      n)
        headcount="$OPTARG"
        if ! [[ "$headcount" =~ ^[0-9]+$ ]]; then
          err "-n argument must be a positive integer"
          return 1
        fi
        shift
        ;;
      :)
        err "option -$OPTARG requires an argument"
        return 1
        ;;
      \?)
        err "Invalid option: -$OPTARG"
        show_help
        return 1
        ;;
    esac
  done
}

validate_directories() {
  # validate directories to search and create array if more than one entered
  #
  # ARG $@: all directories in @
  # RET: array of valid directories

  local dir
  for dir in "$@"; do
    if [[ -d "$dir" ]]; then
      echo "$dir"
    else
      warn "Invalid directory: $dir"
    fi
  done
}

run_sizable_files() {
  # run output command - files
  #
  # ARG $1: $dir, the directory to run from
  # ARG $2: $headcount, the number of files to print

  # using realpath to show a full fs path
  local fpath
  fpath=$(realpath "$1")
  printf "files \t%s\n" "$fpath"
  find "$1" -type f -print0 2>/dev/null \
    | xargs -0 du -h \
    | sort -rh \
    | head -n "$2"
  echo "---"
}

run_sizable_dirs() {
  # run output command - directories
  #
  # ARG $1: $top_dir, the directory to run from
  # ARG $2: headcount, the number of directories to print

  # using realpath to show a full fs path
  local fpath
  fpath=$(realpath "$1")
  printf "dirs \t%s\n" "$fpath"
  find "$1" -type d -print0 2>/dev/null \
    | xargs -0 du -h \
    | sort -rh \
    | head -n "$2"
  echo "---"
}

main () {
  local showed_help headcount="10" show_dirs show_files="1"
  # set default variables for find command
  _parse_options "$@" || exit 1
  [[ "$showed_help" ]] && exit 0
  shift $((OPTIND - 1)) # shift $@ past optional flags

  # verify we have at least one argument after options, if not set it to pwd
  [[ $# -lt 1 ]] && set -- '.'

  for dir in $(validate_directories "$@"); do
    [[ "$show_files" ]] && run_sizable_files "$dir" "$headcount"
    [[ "$show_dirs" ]] && run_sizable_dirs "$dir" $(( headcount + 1 ))
  done
}

main "$@"
